### ISSUE TITLE
Create Debian dpkg build scripts

### ISSUE THREAD

**Issue by chrishoage** [chenxiaolong/ipmi-fan-control#22]
This morning I was researching deb packages and found [cargo deb](https://github.com/mmstick/cargo-deb). I was able to get it set up very quickly. 

When coming here to talk about how you feel about using something like cargo deb in conjunction with something like [Alien](https://wiki.debian.org/Alien) to convert the deb into an rpm I noticed you had committed a build script intended to be used to create system packages. 

I presume you would prefer to use that build script to create the deb package over using a tool like `cargo deb` correct? 

```
› cargo deb --target=x86_64-unknown-linux-gnu
# build stuff
› dpkg -c target/x86_64-unknown-linux-gnu/debian/ipmi-fan-control_0.3.0_amd64.deb     
drwxr-xr-x 0/0               0 2020-12-05 10:12 usr/
drwxr-xr-x 0/0               0 2020-12-05 10:12 usr/share/
drwxr-xr-x 0/0               0 2020-12-05 10:12 usr/share/doc/
drwxr-xr-x 0/0               0 2020-12-05 10:12 usr/share/doc/ipmi-fan-control/
-rw-r--r-- 0/0             171 2020-12-05 10:12 usr/share/doc/ipmi-fan-control/copyright
drwxr-xr-x 0/0               0 2020-12-05 10:12 lib/
drwxr-xr-x 0/0               0 2020-12-05 10:12 lib/systemd/
drwxr-xr-x 0/0               0 2020-12-05 10:12 lib/systemd/system/
-rw-r--r-- 0/0             205 2020-12-05 10:12 lib/systemd/system/ipmi-fan-control.service
drwxr-xr-x 0/0               0 2020-12-05 10:12 usr/bin/
-rwxr-xr-x 0/0         3312056 2020-12-05 10:12 usr/bin/ipmi-fan-control
drwxr-xr-x 0/0               0 2020-12-05 10:12 etc/
-rw-rw-r-- 0/0            3686 2020-12-05 10:12 etc/ipmi-fan-control.toml

```

```diff
diff --git a/Cargo.toml b/Cargo.toml
index 910ad44..4fb8d78 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -8,6 +8,17 @@ version = "0.3.0"
 authors = ["Andrew Gunnerson <andrewgunnerson@gmail.com>"]
 edition = "2018"
 
+
+[package.metadata.deb]
+assets = [
+    ["target/release/ipmi-fan-control", "usr/bin/", "755"],
+    ["config.sample.toml", "etc/ipmi-fan-control.toml", "664"],
+]
+conf-files = ["etc/ipmi-fan-control.toml"]
+maintainer-scripts = "dist/debian/"
+systemd-units = { enable = true }
+
 # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
 
 [dependencies]
diff --git a/dist/debian/ipmi-fan-control.service b/dist/debian/ipmi-fan-control.service
new file mode 100644
index 0000000..f0868c5
--- /dev/null
+++ b/dist/debian/ipmi-fan-control.service
@@ -0,0 +1,10 @@
+[Unit]
+Description=SuperMicro IPMI fan control daemon
+
+[Service]
+ExecStart=/usr/bin/ipmi-fan-control -c /etc/ipmi-fan-control.toml
+Restart=on-failure
+KillMode=process
+
+[Install]
+WantedBy=multi-user.target

```

**Comment by chenxiaolong** [comment]
Oh, that's pretty neat. I hadn't heard of cargo-deb. Do you know if it's able to produce source packages? As I understand it, launchpad.net PPA's do not allow uploading pre-built binary packages. You have to upload the source package which they compile on their servers.

> something like Alien to convert the deb into an rpm I noticed you had committed a build script intended to be used to create system packages.

Fedora's Copr repos also require uploading `src.rpm`'s so unfortunately I don't think that would work. I did find a similar cargo-rpm tool, but I can't tell offhand if it can build source RPMs. I can take a deeper look later.

**Comment by chrishoage** [comment]
No, [it does not appear to be able to create a source package](https://github.com/mmstick/cargo-deb/issues/40), just binary debs that can be distributed. However that GHI links to [debcargo which can](https://salsa.debian.org/rust-team/debcargo) however a quick scroll through makes it seem more complex. 

I'll read through the following documentation below when I have a bit more time to figure out how to roll our own 

https://help.launchpad.net/Packaging/PPA/BuildingASourcePackage
https://www.debian.org/doc/debian-policy/ch-source.html
https://debian-handbook.info/browse/stable/sect.source-package-structure.html

**Comment by chrishoage** [comment]
I've spent a while on this and I'm not much closer. Packaging in Debian is a huge headache compared to `PKGBUILD` and RPM. 

There are strict rules around changelog structure, inability to use cargo to install build deps (at least as far as I can tell you must use apt provided build deps). Even using something like `debcargo` is complex, and I still wasn't able to get it to build properly due to the build requirements. 

I might recommended you reconsider hosting built deb binaries on github packages and users can install that way.

I'll work on a `PKGBUILD` as that will be much simpler (though not useful to me personally)

**Comment by chenxiaolong** [comment]
Hmm, doesn't sound like much has changed since the last time I tried to build a deb package years ago :(

I'll poke around and see if I can figure something out. I'd imagine there must be some way to run a generic `cargo build` (possibly avoiding any deb+cargo integration that might exist?). That's what I did for the Fedora package and I enabled the "Allow internet access during build" option on their build service.

If I can't figure something out, I'll just use cargo-deb and upload the binaries to GitHub.

**Comment by chrishoage** [comment]
I'll be curious how it goes. 

I used https://wiki.debian.org/Teams/RustPackaging/Policy and https://salsa.debian.org/rust-team/debcargo-conf for references when trying to correctly package this software. 

I was able to get debcargo-conf to create a sdist, however I was unable to get it to build

**Comment by chenxiaolong** [comment]
I got something working locally! (#26) I ended up starting with:

```bash
DEBFULLNAME=none DEBEMAIL=none@none.none debcargo package ripgrep
```

and then modifying all the files to work for ipmi-fan-control. These were the main changes I made:

* Deleted `debian/changelog` and updated `build_source_package.sh` to generate a dummy line using the `dch` tool
* Removed all `librust-*-dev` dependencies in `debian/control`
* Removed all the autogenerated `${cargo:*}` variables in `debian/control`
* Removed the `dh-cargo` dependency in `debian/control` and `--buildsystem cargo` in `debian/rules` to avoid any debhelper/cargo integration
* Used `override_dh_auto_{configure,build,clean}` and `override_dh_installsystemd` rules in `debian/rules` to do the manual `cargo build`
* Manually created the `debian/copyright` file

It was frustrating how much stuff was done automatically/implicitly... I like Debian and Ubuntu, but the packaging is way more difficult to understand than RPM specs and PKGBUILDs. I ended up using these docs as a reference:

* https://wiki.debian.org/Packaging/Intro - Basic docs for creating a package from scratch.
* https://manpages.debian.org/unstable/debhelper/debhelper.7.en.html - Contains a list of debhelper stages that can be overridden in `debian/rules`.
* https://manpages.debian.org/unstable/debhelper/dh_install.1.en.html - Docs on how to use `debian/<package>.install` for installing files without manually running `install -Dm644 ...` in `debian/rules`.
* https://manpages.debian.org/unstable/debhelper/dh_installsystemd.1.en.html - Docs for the tool that automatically puts `debian/<package>.service` in `/lib/systemd/system` and creates the appropriate pre/post-install hooks.
* https://www.debian.org/doc/debian-policy/ch-controlfields.html - List of ~all~ most valid `debian/control` fields. I couldn't find docs for some of the fields that debcargo adds.
* https://www.debian.org/doc/manuals/debmake-doc/ch05.en.html - Decent descriptions of what all the `debian/*` files are for.

With the new build scripts, I can generate the source package and build a deb from it with:

```bash
./dist/build_source_package.sh -t debsrc
mkdir temp
cd temp
dpkg-source -x ../dist/output/debian/ipmi-fan-control_0.3.0.r8.git2d545e3-1.dsc
cd ipmi-fan-control-0.3.0.r8.git2d545e3
debuild -us -uc
sudo dpkg -i ../ipmi-fan-control_0.3.0.r8.git2d545e3-1_amd64.deb
```

All I have left to do is to figure out how to get this pushed to a launchpad.net PPA.

**Comment by chrishoage** [comment]
> Removed all librust-*-dev dependencies in debian/control

This is where I got stuck. I was drowning in documentation and didn't know what was possible and what wasn't.

> It was frustrating how much stuff was done automatically/implicitly... I like Debian and Ubuntu, but the packaging is way more difficult to understand than RPM specs and PKGBUILDs. 

:100: 



I'll test out https://github.com/chenxiaolong/ipmi-fan-control/pull/26 right now

**Comment by chenxiaolong** [comment]
Completed in #26
