### ISSUE TITLE
unable to send RAW command

### ISSUE THREAD

**Issue by internetuser22** [chenxiaolong/ipmi-fan-control#41]
sudo ipmi-fan-control --config /etc/ipmi-fan-control.toml
[2022-05-07T00:23:10Z ERROR ipmi_fan_control] IPMI error: Failed to parse line 'Unable to send RAW command (channel=0x0 netfn=0x30 lun=0x0 cmd=0x45 rsp=0xc1): Invalid command
    ': invalid digit found in string

**Comment by chenxiaolong** [comment]
Hmm, that message (`Unable to send RAW command (channel=0x0 netfn=0x30 lun=0x0 cmd=0x45 rsp=0xc1): Invalid command`) comes directly from `ipmitool`. Which Supermicro motherboard do you have?

If the specific model doesn't support these raw fan zone control commands, then unfortunately, ipmi-fan-control won't work.

**Comment by internetuser22** [comment]
ok sorry for the confusion its a DELL server MB thanks for reply
