### ISSUE TITLE
tune log level/verbosity

### ISSUE THREAD

**Issue by gyakovlev** [chenxiaolong/ipmi-fan-control#49]
Hey, thanks for great software.
works wonderfully with my [H12DSi-NT6](https://www.supermicro.com/en/products/motherboard/H12DSi-NT6)
I added package to gentoo linux repo https://packages.gentoo.org/packages/sys-apps/ipmi-fan-control

my question is:

currently default loglevel is `INFO`
```
Sep 14 14:37:19 chimera ipmi-fan-control[1482167]: [2022-09-14T21:37:19Z INFO  ipmi_fan_control] [default] Zone 1: zone_temp=53C, dcycle_cur=25%, dcycle_new=26%
Sep 14 14:37:20 chimera ipmi-fan-control[1482167]: [2022-09-14T21:37:20Z INFO  ipmi_fan_control] [default] Zone 0: zone_temp=54C, dcycle_cur=35%, dcycle_new=38%
```
it prints status every interval.

but if I launch it  with `RUST_LOG=warn` envvar - it's completely silent.

what I propose it change startup/shutdown messages to `warn`, so users who run it with `warn` loglevel still see startup message and shutdown message when it restores BMC settings, but not every loop interval report.
WDYT about such change?

**Comment by chenxiaolong** [comment]
Thanks for creating the Gentoo package!

I think this is a good idea, but I'm thinking about approaching it a different way. Maybe something like:

* change the current `debug` messages to `trace`
* change the current `info` messages to `debug`
* keep the fan mode startup/shutdown messages at the `info` level

I'd prefer to keep `warn` for logging recoverable errors.

**Comment by gyakovlev** [comment]
that was second thought as well, changing current status heartbeats to DEBUG. basically make it a little less verbose by default but still debug-able and configurable is all I'm after.
those INFO messages are very useful to tune the curve but not really needed after tuning is done. but startup/shutdown/major messages are good to have at runtime.


also `.service.in` file can be updated to contain a commented-out `#Enviroment="RUST_LOG=info"` line so people know how to tune it, not everyone knows about `env_logger`

**Comment by chenxiaolong** [comment]
That seems reasonable. When I implement this, I'll add a comment to the systemd service file and also add a section about it to the README.

**Comment by chenxiaolong** [comment]
On second thought, I wonder if the log level should be an option in the config file. Then the user wouldn't have to edit the systemd service to set `RUST_LOG`.

**Comment by gyakovlev** [comment]
thanks!
tested, works great and is quiet, both in logs and under desk.

```Hack
Sep 15 18:34:43 chimera ipmi-fan-control[2696392]: [INFO  ipmi_fan_control] [default] Original fan mode: Optimal
Sep 15 18:34:43 chimera ipmi-fan-control[2696392]: [INFO  ipmi_fan_control] [default] Setting fan mode to: Full
Sep 15 18:34:43 chimera ipmi-fan-control[2696392]: [INFO  ipmi_fan_control] [default] Starting loop for IPMI zones [0]
Sep 15 18:34:43 chimera ipmi-fan-control[2696392]: [INFO  ipmi_fan_control] [default] Starting loop for IPMI zones [1]
Sep 15 18:35:03 chimera systemd[1]: Stopping SuperMicro IPMI fan control daemon...
Sep 15 18:35:03 chimera ipmi-fan-control[2696392]: [INFO  ipmi_fan_control] Interrupted
Sep 15 18:35:03 chimera ipmi-fan-control[2696392]: [INFO  ipmi_fan_control] [default] Setting zone 0 duty cycle to 100%
Sep 15 18:35:03 chimera ipmi-fan-control[2696392]: [INFO  ipmi_fan_control] [default] Setting zone 1 duty cycle to 100%
Sep 15 18:35:03 chimera ipmi-fan-control[2696392]: [INFO  ipmi_fan_control] [default] Restoring fan mode to: Optimal
Sep 15 18:35:04 chimera systemd[1]: ipmi-fan-control.service: Deactivated successfully.
```
