### ISSUE TITLE
Version 0.4.0 doesn't read HDD temperature via SMART

### ISSUE THREAD

**Issue by stigger** [chenxiaolong/ipmi-fan-control#62]
It just fails, no actual attempts are visible in the log:
```
[INFO  ipmi_fan_control] [default] Original fan mode: Full
[INFO  ipmi_fan_control] [default] Starting loop for IPMI zones [0]
[INFO  ipmi_fan_control] [default] Starting loop for IPMI zones [1]
[DEBUG ipmi_fan_control] [default] Zone 0: zone_temp=33C, dcycle_cur=100%, dcycle_new=21%
[INFO  ipmi_fan_control] [default] Setting zone 0 duty cycle to 100%
[INFO  ipmi_fan_control] [default] Setting zone 1 duty cycle to 100%
[ERROR ipmi_fan_control] Failed all 3 attempt(s); last attempt error: Block device has no temperature reading: "/dev/sda"
```

**Comment by chenxiaolong** [comment]
If you run `sudo smartctl -j -A -n standby /dev/sda`, is there a `temperature` -> `current` field?

0.4.0 didn't change anything related to the smartctl command, but it did change the behavior so that it no longer ignores drives with no temperature values. I wonder if that's why you're encountering this.

(Also, I'll find a way to log the first 2 attempts as well)

**Comment by stigger** [comment]
No, when the device is in standby there is no temperature field, `smartctl` reports the temperature only when the device is active. `hdparm -H /dev/sda` reports it even in standby mode, though, but that method is not universal.

**Comment by chenxiaolong** [comment]
If that's the case, I wonder if the best way forward is to add a new `type = "hdparm"` source or something like that.

**Comment by stigger** [comment]
That would be a perfect solution for me, although I wonder, if there are any drives which support neither `hdparm` reporting, nor `smartctl` in standby.

**Comment by chenxiaolong** [comment]
That's a good question, I'm not sure. Out of curiosity, if you `modprobe drivetemp` and run `sensors`, is it able to show the temperature of the spun-down drives?

**Comment by stigger** [comment]
I don't have this module (RHEL 9).

**Comment by chenxiaolong** [comment]
Could you give the `hdparm` branch a try? (I assume you compile from source since you're on RHEL 9.) The only config change that's needed is `type = "smart"` -> `type = "hdparm"`.

(EDIT: branch was updated to fix compilation on slightly older versions of Rust)

**Comment by stigger** [comment]
Actually, normally I use Fedora_36 repo, and before that I used CentOS_7. But I compiled from `hdparm` branch and it seems to be working well. Thank you again!

**Comment by chenxiaolong** [comment]
Great, thanks for testing! I'll merge that branch and release 0.4.1 with the changes later today.
