### ISSUE TITLE
ipmi-fan-control leaves thousands of hdparm zombies

### ISSUE THREAD

**Issue by stigger** [chenxiaolong/ipmi-fan-control#65]
```
[root@home]/home/stigger# ps x|grep hdparm|wc -l
55870
```

**Comment by chenxiaolong** [comment]
Dang it, I bet I forgot a `waitpid` again. I'll fix this shortly.

EDIT:

```
[19:16:08] chenxiaolong@sm-1 ~ took 3s182ms
❯ ps aux | grep -i hdparm | wc -l
99297
```

TIL I can make htop use 100% CPU 
![image](https://user-images.githubusercontent.com/646253/192654133-3997285c-c959-49c3-ac8e-2ac5b31e89ab.png)
